### ISSUE TITLE
Bad URL

### ISSUE THREAD

**Issue by kalepail** [orbitlens/stellar-turing-server-dashboard#2]
GET https://turing-signing-server-0.stellar.buzz/contract 
should be just 
GET https://turing-signing-server-0.stellar.buzz

There may be others but at least that route should be fixed. I think https://www.notion.so/Turing-Signing-Servers-661f3ff0de5143c1bd3c6fb52ae88dae is up to date now.

**Comment by orbitlens** [comment]
Could you please clarify where you can see this? I updated the urls to fetch directly from the `/` route instead of `/contract` 3 weeks ago.

And everything seems to be working here: https://tss-dashboard.stellar.expert/turret/https%3A%2F%2Fturing-signing-server-4.stellar.buzz%2F

Am I missing something?

**Comment by kalepail** [comment]
I'm trying to upload a contract. Looks like it's not the url though. Something else is up. Let me try and upload outside your UI.

![Screen Shot 2020-08-25 at 4 44 49 PM](https://user-images.githubusercontent.com/4383610/91225982-65a4e180-e6f2-11ea-83cb-1b639459be52.png)

**Comment by kalepail** [comment]
Ah looks like the turrets list isn't being base64 encoded. It needs to be encoded in the same way the fields list is.

**Comment by kalepail** [comment]
![Screen Shot 2020-08-25 at 5 00 21 PM](https://user-images.githubusercontent.com/4383610/91227430-7a827480-e6f4-11ea-9675-1c36851013b9.png)

**Comment by kalepail** [comment]
`turrets` should look something like `aHR0cHM6Ly90dXJpbmctc2lnbmluZy1zZXJ2ZXItNC5zdGVsbGFyLmJ1enovLGh0dHBzOi8vdHVyaW5nLXNpZ25pbmctc2VydmVyLTMuc3RlbGxhci5idXp6LyxodHRwczovL3R1cmluZy1zaWduaW5nLXNlcnZlci0yLnN0ZWxsYXIuYnV6ei8=`

**Comment by orbitlens** [comment]
Fixed in 0.1.3 - 7180c0dcf7f8e9b959cf6b51c658464cafa235f4

**Comment by kalepail** [comment]
Awesome! Has this been deployed?

**Comment by orbitlens** [comment]
I configured an autodeploy workflow, so everything is automatically get deployed on each commit to `master`.

**Comment by kalepail** [comment]
Works like a charm. I've got an idea for signer swapping I'm excited to float past you once I work out a demo.
